version: '3.3'
services:
  database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'test'
      POSTGRES_DB: 'test'
    networks:
      - backend
    ports:
      - "5432:5432"
    volumes:
      - database-pg:/var/lib/postgresql/data

networks:
  backend:
    driver: bridge

volumes:
  database-pg: